[phases.setup]
nixPkgs = ["python311", "nodejs", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput --clear",
    "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn alhassan.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"

[variables]
DJANGO_SETTINGS_MODULE = "alhassan.settings"
PYTHONPATH = "."
DEBUG = "False"
WSGI_APPLICATION = "alhassan.wsgi.application"
