[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn alhassan.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
DJANGO_SETTINGS_MODULE = "alhassan.settings"
PYTHONPATH = "."
DEBUG = "False"
STUDENT_ACCESS_CODE = "ben25"
